// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa68zXmLoZ5azcUPQ_oXmvLdsV2nLy2UY',
    appId: '1:209344773710:web:d1fd9b26dfd8b78e2d4d1f',
    messagingSenderId: '209344773710',
    projectId: 'andit-369422',
    authDomain: 'andit-369422.firebaseapp.com',
    storageBucket: 'andit-369422.appspot.com',
    measurementId: 'G-EKDZDP01NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOG0CyGMQFVhCA4cZL0ClaE63LdxUf4hA',
    appId: '1:209344773710:android:45041660b5abead32d4d1f',
    messagingSenderId: '209344773710',
    projectId: 'andit-369422',
    storageBucket: 'andit-369422.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjX8FgWc1e7dEYJZkyX-zcp90pjMBwySg',
    appId: '1:209344773710:ios:1c524360a2d6ee342d4d1f',
    messagingSenderId: '209344773710',
    projectId: 'andit-369422',
    storageBucket: 'andit-369422.appspot.com',
    iosClientId: '209344773710-lv3vmej6ros7d27500vk5kksqib5tg8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.andit.andit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjX8FgWc1e7dEYJZkyX-zcp90pjMBwySg',
    appId: '1:209344773710:ios:1c524360a2d6ee342d4d1f',
    messagingSenderId: '209344773710',
    projectId: 'andit-369422',
    storageBucket: 'andit-369422.appspot.com',
    iosClientId: '209344773710-lv3vmej6ros7d27500vk5kksqib5tg8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.andit.andit',
  );
}
